# Generated by Django 4.1.4 on 2022-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
