# Generated by Django 4.1.4 on 2022-12-12 01:52

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=todo_app.models.one_week_hence),
        ),
    ]
