# Generated by Django 4.1.4 on 2022-12-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='code',
        ),
    ]
